[profile.default]
bytecode_hash = "none"
optimizer_runs = 1000000
timeout = 10000
block_gas_limit = 30000000
gas_limit = 3000000000
gas_price = 1500000000

solc_version = "0.8.19"

fs_permissions = [{ access = "read-write", path = "./"}]