[profile.default]
bytecode_hash = "none"
optimizer_runs = 200
timeout = 30000
block_gas_limit = 300000000
gas_limit = 3000000000
gas_price = 1500000000

solc_version = "0.8.21"

fs_permissions = [{ access = "read-write", path = "./"}]