[profile.default]
bytecode_hash = "none"
optimizer_runs = 20
timeout = 30000
block_gas_limit = 300000000
gas_limit = 3000000000
gas_price = 1500000000

solc_version = "0.8.18"
evm_version = 'paris'

fs_permissions = [{ access = "read-write", path = "./"}]